image: Visual Studio 2017
before_build:
  - cmd: dotnet restore library/ref
  - cmd: dotnet restore library/src
  - ps: . .\download_resources.ps1
# build:
#   publish_nuget: true
#   parallel: true
#   verbosity: minimal
build_script:
  - dotnet build library/ref -c Release
  - dotnet build library/src -c Release
  - dotnet build library/src -c iOS_Release

after_build:
  - nuget pack library/nuget/DotnetWorld.nuspec

artifacts:
  - path: /DotnetWorld*.nupkg/
    name: Nupkg

deploy:
  provider: GitHub
  auth_token:
    secure: "phbIUL1pW4otTYZTo79JgBo7dznsGhCGU3Jbs8jLhM482kySCkP2oXWofXKMPqtc"
  artifact: Nupkg
  on:
    appveyor_repo_tag: true
  force_update: true